apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskly-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskly-backend
  template:
    metadata:
      labels:
        app: taskly-backend
    spec:
      containers:
        - name: taskly-backend
          image: taskly-backend
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: taskly-secrets
